name: ci

env:
  R2V: 5.9.0

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build-linux22:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Installing radare2
      run: |
        git clone --depth=1 https://github.com/radareorg/radare2 && cd radare2
        sys/install.sh
    - name: Installing yara and r2yara via r2pm
      run: r2pm -Uci r2yara
    - name: Testing r2yara installation
      run: R2_DEBUG=1 r2 -qcq -c 'yrv' --
    - name: Running Testsuite
      run: make -C test
